from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(361, 588)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.outputlabel = QtWidgets.QLabel(self.centralwidget)
        self.outputlabel.setGeometry(QtCore.QRect(10, 10, 341, 91))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.outputlabel.setFont(font)
        self.outputlabel.setFrameShape(QtWidgets.QFrame.Box)
        self.outputlabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.outputlabel.setLineWidth(2)
        self.outputlabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.outputlabel.setObjectName("outputlabel")
        self.percentbutton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press_it("%"))
        self.percentbutton.setGeometry(QtCore.QRect(10, 110, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.percentbutton.setFont(font)
        self.percentbutton.setObjectName("percentbutton")
        self.cbutton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press_it("C"))
        self.cbutton.setGeometry(QtCore.QRect(100, 110, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.cbutton.setFont(font)
        self.cbutton.setObjectName("cbutton")
        self.arrowbutton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.remove_it())
        self.arrowbutton.setGeometry(QtCore.QRect(190, 110, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.arrowbutton.setFont(font)
        self.arrowbutton.setObjectName("arrowbutton")
        self.dividebutton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press_it("/"))
        self.dividebutton.setGeometry(QtCore.QRect(280, 110, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.dividebutton.setFont(font)
        self.dividebutton.setObjectName("dividebutton")
        self.timesbutton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press_it("*"))
        self.timesbutton.setGeometry(QtCore.QRect(280, 200, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.timesbutton.setFont(font)
        self.timesbutton.setObjectName("timesbutton")
        self.sevenbutton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press_it("7"))
        self.sevenbutton.setGeometry(QtCore.QRect(10, 200, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.sevenbutton.setFont(font)
        self.sevenbutton.setObjectName("sevenbutton")
        self.eightbutton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press_it("8"))
        self.eightbutton.setGeometry(QtCore.QRect(100, 200, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.eightbutton.setFont(font)
        self.eightbutton.setObjectName("eightbutton")
        self.ninebutton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press_it("9"))
        self.ninebutton.setGeometry(QtCore.QRect(190, 200, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.ninebutton.setFont(font)
        self.ninebutton.setObjectName("ninebutton")
        self.minusbutton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press_it("-"))
        self.minusbutton.setGeometry(QtCore.QRect(280, 290, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.minusbutton.setFont(font)
        self.minusbutton.setObjectName("minusbutton")
        self.twobutton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press_it("2"))
        self.twobutton.setGeometry(QtCore.QRect(100, 380, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.twobutton.setFont(font)
        self.twobutton.setObjectName("twobutton")
        self.plusbutton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press_it("+"))
        self.plusbutton.setGeometry(QtCore.QRect(280, 380, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.plusbutton.setFont(font)
        self.plusbutton.setObjectName("plusbutton")
        self.threebutton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press_it("3"))
        self.threebutton.setGeometry(QtCore.QRect(190, 380, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.threebutton.setFont(font)
        self.threebutton.setObjectName("threebutton")
        self.fourbutton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press_it("4"))
        self.fourbutton.setGeometry(QtCore.QRect(10, 290, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.fourbutton.setFont(font)
        self.fourbutton.setObjectName("fourbutton")
        self.onebutton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press_it("1"))
        self.onebutton.setGeometry(QtCore.QRect(10, 380, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.onebutton.setFont(font)
        self.onebutton.setObjectName("onebutton")
        self.fivebutton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press_it("5"))
        self.fivebutton.setGeometry(QtCore.QRect(100, 290, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.fivebutton.setFont(font)
        self.fivebutton.setObjectName("fivebutton")
        self.sixbutton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press_it("6"))
        self.sixbutton.setGeometry(QtCore.QRect(190, 290, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.sixbutton.setFont(font)
        self.sixbutton.setObjectName("sixbutton")
        self.plusminusbutton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.plus_minus_it())
        self.plusminusbutton.setGeometry(QtCore.QRect(10, 470, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.plusminusbutton.setFont(font)
        self.plusminusbutton.setObjectName("plusminusbutton")
        self.zerobutton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press_it("0"))
        self.zerobutton.setGeometry(QtCore.QRect(100, 470, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.zerobutton.setFont(font)
        self.zerobutton.setObjectName("zerobutton")
        self.dotbutton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.dot_it())
        self.dotbutton.setGeometry(QtCore.QRect(190, 470, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.dotbutton.setFont(font)
        self.dotbutton.setObjectName("dotbutton")
        self.equalbutton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.math_it())
        self.equalbutton.setGeometry(QtCore.QRect(280, 470, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.equalbutton.setFont(font)
        self.equalbutton.setObjectName("equalbutton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 361, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def math_it(self):
        screen = self.outputlabel.text()
        try:
            answer = eval(screen)
            self.outputlabel.setText(str(answer))
        except:
            self.outputlabel.setText("ERROR")
    def plus_minus_it(self):
        screen = self.outputlabel.text()
        if "-" in screen:
            self.outputlabel.setText(screen.replace("-",""))
        else:
            self.outputlabel.setText(f'-{screen}')
    def remove_it(self):
        screen = self.outputlabel.text()
        screen = screen[:-1]
        self.outputlabel.setText(screen)
    def dot_it(self):
        screen = self.outputlabel.text()
        if screen[-1] == ".":
            pass
        else:
             self.outputlabel.setText(f'{screen}.')

    def press_it(self,pressed):
        if pressed == 'C':
            self.outputlabel.setText("0")
        else:
            if self.outputlabel.text() == "0":
                self.outputlabel.setText("")
            self.outputlabel.setText(f'{self.outputlabel.text()}{pressed}')

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.outputlabel.setText(_translate("MainWindow", "0"))
        self.percentbutton.setText(_translate("MainWindow", "%"))
        self.cbutton.setText(_translate("MainWindow", "C"))
        self.arrowbutton.setText(_translate("MainWindow", "<<"))
        self.dividebutton.setText(_translate("MainWindow", "/"))
        self.timesbutton.setText(_translate("MainWindow", "x"))
        self.sevenbutton.setText(_translate("MainWindow", "7"))
        self.eightbutton.setText(_translate("MainWindow", "8"))
        self.ninebutton.setText(_translate("MainWindow", "9"))
        self.minusbutton.setText(_translate("MainWindow", "-"))
        self.twobutton.setText(_translate("MainWindow", "2"))
        self.plusbutton.setText(_translate("MainWindow", "+"))
        self.threebutton.setText(_translate("MainWindow", "3"))
        self.fourbutton.setText(_translate("MainWindow", "4"))
        self.onebutton.setText(_translate("MainWindow", "1"))
        self.fivebutton.setText(_translate("MainWindow", "5"))
        self.sixbutton.setText(_translate("MainWindow", "6"))
        self.plusminusbutton.setText(_translate("MainWindow", "+/-"))
        self.zerobutton.setText(_translate("MainWindow", "0"))
        self.dotbutton.setText(_translate("MainWindow", "."))
        self.equalbutton.setText(_translate("MainWindow", "="))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
